# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  CI:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Autenticação no Docker Hub       
        uses: docker/login-action@v2.0.0
        with:                   
          username: ${{secrets.DOCKERHUB_USER}}         
          password: ${{secrets.DOCKERHUB_PWD}}        
      
      - name: Construção da imagem e push para Docker Hub        
        uses: docker/build-push-action@v3.1.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            guigapc/kube-news:latest
            guigapc/kube-news:${{github.run_number}}

  CD:    
    runs-on: ubuntu-latest
    needs: [CI]    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Definindo KubeConfig
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBE_CONFIG}}
      
      - name: Deploy para DigitalOcean
        uses: Azure/k8s-deploy@v4.3
        with:
          images: guigapc/kube-news:${{github.run_number}}
          manifest: |
            k8s/deployment.yaml
          
    
